# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=66)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'simpleUser'), (2, 'vipUser'), (3, 'svipUser')])),
                ('user_name', models.CharField(max_length=66, unique=True)),
                ('password', models.CharField(max_length=66)),
                ('user_Role', models.ManyToManyField(to='api.Role')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserToker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=66, null=True)),
                ('user_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
    ]
