# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, 'vipUser'), (3, 'svipUser')]),
        ),
    ]
